language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Arithmetic-expressions
  - make -j
  - cd ./bin/
  - ./test_stack
notifications:
  email: false
